# -*- coding: utf-8 -*-
"""serve/first_run.py — 首次运行向导（懒人式一键）。

目标：用户解压后只需要双击 START.bat —— 剩下的（装依赖、下载权重、校验数据、
写好路径配置、启动对话）全部自动完成。

为什么要有它（2026-10-01）：本包**不含模型权重**（49.1 GB 量化包 + 335 GB 上游基座），
而引擎只认"一个目录 + 固定文件名"。如果让用户自己找目录、自己改环境变量、
自己判断版本对不对，第一次体验必然是失败的。

设计原则：
  · 不静默下载几百 GB —— 先打印"要下什么、多大、下到哪"，要用户确认（`--yes` 可跳过）
  · 可中断可重跑 —— modelscope 自带断点续传；每次运行只补缺失的部分
  · 先查磁盘空间 —— 不足时**提前**报错，而不是下到一半撑爆
  · 校验而不是相信 —— 用 MANIFEST.json 里的小文件 sha256 判上游版本对不对

用法:
    python serve\\first_run.py                # 交互式向导（推荐）
    python serve\\first_run.py --yes          # 不提问（无人值守）
    python serve\\first_run.py --check-only   # 只校验与写配置，不下载
"""
import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# ---------------------------------------------------------------------------
# 发布件坐标（改这里就能换源）
# ---------------------------------------------------------------------------
K3_REPO = os.environ.get("ARKION_K3_REPO", "HQsensei/Arkion-Q1-K3")     # 我们量化的 49.1 GB 包
K3_FILES = 52          # 48 专家包 + 4 个权重/索引
K3_GB = 49.1
# 上游基座（PLE 真表来源）。它在魔搭上的仓库 id 必须由发布者填：
#   从你当初下载 D:\qwen3.8-flash-next 的那个魔搭页面复制 owner/name 即可。
UPSTREAM_REPO = os.environ.get("ARKION_UPSTREAM_REPO", "").strip()
UPSTREAM_GB = 335.3
PIP_DEPS = ["tokenizers", "jinja2"]


def hr(t=""):
    print("\n" + "=" * 68)
    if t:
        print("  " + t)
        print("=" * 68)


def ask(msg, default_no=True):
    try:
        a = input("%s [%s]: " % (msg, "y/N" if default_no else "Y/n")).strip().lower()
    except EOFError:
        return not default_no
    if not a:
        return not default_no
    return a in ("y", "yes")


def free_gb(path):
    try:
        d = os.path.splitdrive(os.path.abspath(path))[0] + os.sep
        return shutil.disk_usage(d).free / 2**30
    except Exception:
        return -1.0


def have_cli(name):
    return shutil.which(name) is not None


def step_deps(auto_yes):
    hr("[1/5] Python 依赖")
    try:
        import tokenizers  # noqa: F401
        import jinja2      # noqa: F401
        print("  tokenizers / jinja2 已就绪")
        return True
    except ImportError:
        pass
    print("  缺少: %s" % ", ".join(PIP_DEPS))
    if not auto_yes and not ask("  现在用 pip 安装？"):
        print("  跳过（服务层会起不来）。可手动: python -m pip install %s" % " ".join(PIP_DEPS))
        return False
    r = subprocess.call([sys.executable, "-m", "pip", "install", "--quiet",
                         "--disable-pip-version-check"] + PIP_DEPS)
    print("  pip 返回 %d" % r)
    return r == 0


def read_local_cfg():
    """读 arkion.local.bat（由本脚本或 locate_model.py --write 生成）。"""
    p = os.path.join(ROOT, "arkion.local.bat")
    cfg = {}
    if not os.path.isfile(p):
        return cfg
    for line in open(p, encoding="ascii", errors="replace"):
        line = line.strip()
        if line.lower().startswith("set "):
            k, _, v = line[4:].partition("=")
            cfg[k.strip().upper()] = v.strip()
    return cfg


def write_local_cfg(model_dir, ple_root, pack="experts_k3c"):
    p = os.path.join(ROOT, "arkion.local.bat")
    with open(p, "w", encoding="ascii", newline="\r\n") as f:
        f.write("@echo off\r\n")
        f.write("REM generated by serve/first_run.py - machine specific, do not commit\r\n")
        f.write("set ARK_MODEL_DIR=%s\r\n" % model_dir)
        if ple_root:
            f.write("set ARK_PLE_ROOT=%s\r\n" % ple_root)
        if pack:
            f.write("set K4_PACK_DIR=%s\r\n" % pack)
    print("  已写入 %s" % p)


def ms_download(repo, local_dir, workers=4):
    cmd = ["modelscope", "download", repo, "--local-dir", local_dir,
           "--repo-type", "model", "--max-workers", str(workers)]
    print("  $ " + " ".join(cmd))
    return subprocess.call(cmd)


def count_k3(model_dir, pack="experts_k3c"):
    n = 0
    d = os.path.join(model_dir, pack)
    for li in range(48):
        if os.path.isfile(os.path.join(d, "L%02d_%s.bin" % (li, pack))):
            n += 1
    return n


def verify_upstream(ple_root, man):
    """用 MANIFEST 的上游指纹判版本（长度 + 小文件 sha256）。

    返回 True=校验通过 / False=不符 / None=**没有指纹可用**。
    必须区分后两者：把"没检查"说成"检查通过"是最危险的输出 —— 用户会以为
    版本对得上，而实际现象是引擎不报错、只解码出垃圾。
    """
    up = (man or {}).get("upstream") or {}
    small = up.get("small") or {}
    checked = sum(1 for d in small.values() if d)
    if checked == 0:
        print("  ⚠ 没有可用的上游指纹（MANIFEST.json 缺失或为空）⇒ **无法判断版本是否匹配**。")
        print("    权重包（魔搭）里带 MANIFEST.json，把它放到本目录后重跑即可校验；")
        print("    或自行核对：上游有 %s 个 safetensors、共约 %.1f GB。"
              % (up.get("safetensors_count", "?"), (up.get("safetensors_total_bytes") or 0) / 2**30))
        return None
    bad = []
    for name, d in small.items():
        if not d:
            continue
        p = os.path.join(ple_root, name)
        if not os.path.isfile(p):
            bad.append("%s 缺失" % name)
            continue
        if os.path.getsize(p) != d.get("bytes"):
            bad.append("%s 长度不符" % name)
            continue
        want = d.get("sha256")
        if want:
            h = hashlib.sha256()
            with open(p, "rb") as f:
                for b in iter(lambda: f.read(64 << 20), b""):
                    h.update(b)
            if h.hexdigest() != want:
                bad.append("%s sha256 不符" % name)
    if bad:
        print("  ✗ 上游版本校验未通过：")
        for b in bad[:5]:
            print("      - " + b)
        print("    ⇒ 这**不是**可以忽略的警告：ple_index.json 记的是到上游分片的精确字节偏移，")
        print("      版本不符时引擎不报错，只会解码出垃圾。请重下正确的 revision。")
        return False
    print("  ✓ 上游版本校验通过（%d 个小文件一致）" % len([1 for d in small.values() if d]))
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--yes", action="store_true", help="不提问，直接执行")
    ap.add_argument("--check-only", action="store_true", help="只校验/写配置，不下载")
    ap.add_argument("--model-dir", default=None, help="K3 包存放目录")
    ap.add_argument("--ple-root", default=None, help="上游基座目录")
    a = ap.parse_args()

    hr("Arkion-Q1 v0.0.1-preview —— 首次运行向导")
    print("  本软件为**闭源预览版，按现状提供、无担保**。继续即表示你已阅读 EULA.md。")
    print("  本包**不含模型权重**（约 49 GB 量化包 + 约 335 GB 上游基座）。")
    if not a.yes:
        if not ask("  同意并继续？"):
            print("  已取消。")
            return 0

    # ---- 1) 依赖 ----
    step_deps(a.yes)

    # ---- 2) 决定目录 ----
    hr("[2/5] 模型位置")
    cfg = read_local_cfg()
    model_dir = a.model_dir or cfg.get("ARK_MODEL_DIR") or os.environ.get("ARK_MODEL_DIR")
    ple_root = a.ple_root or cfg.get("ARK_PLE_ROOT") or os.environ.get("ARK_PLE_ROOT")
    print("  当前 ARK_MODEL_DIR = %s" % (model_dir or "(未设置)"))
    print("  当前 ARK_PLE_ROOT  = %s" % (ple_root or "(未设置)"))

    if not model_dir:
        # 默认放剩余空间最大的固定盘
        best, bestfree = None, -1
        for c in "CDEFGH":
            g = free_gb("%s:\\" % c)
            if g > bestfree:
                best, bestfree = c, g
        dflt = "%s:\\arkion-q1-k3" % (best or "E")
        print("  未配置。建议存放位置: %s（该盘剩余 %.0f GB）" % (dflt, bestfree))
        if a.yes:
            model_dir = dflt
        else:
            try:
                t = input("  输入 K3 包目录（回车用建议值）: ").strip().strip('"')
            except EOFError:
                t = ""
            model_dir = t or dflt

    need = K3_GB if count_k3(model_dir) < 48 else 0.0
    if need:
        fg = free_gb(model_dir)
        print("  K3 包需要约 %.1f GB，该盘剩余 %.1f GB" % (need, fg))
        if 0 <= fg < need + 5:
            print("  ✗ 空间不足。换一个盘，或先清理。")
            return 2

    # ---- 3) 下载 K3 包 ----
    hr("[3/5] K3 量化包")
    n = count_k3(model_dir)
    print("  已有 %d/48 个专家包" % n)
    if n < 48:
        if a.check_only:
            print("  --check-only：跳过下载。")
        elif not have_cli("modelscope"):
            print("  ✗ 未安装 modelscope CLI。请先执行：")
            print("      python -m pip install modelscope")
            print("    然后重新运行本向导，或手动下载：")
            print("      modelscope download %s --local-dir \"%s\"" % (K3_REPO, model_dir))
            return 3
        else:
            if a.yes or ask("  现在从魔搭下载 %s（%.1f GB）？" % (K3_REPO, K3_GB)):
                ms_download(K3_REPO, model_dir, workers=4)
    print("  现在 %d/48" % count_k3(model_dir))

    # ---- 4) 上游基座（PLE） ----
    hr("[4/5] 上游基座（PLE 真表来源）")
    man = None
    for mp in (os.path.join(ROOT, "MANIFEST.json"),          # 发布包根目录（make_dist 会放）
               os.path.join(model_dir or "", "MANIFEST.json"),  # 权重包里也带一份
               os.path.join(ROOT, "ms_pack_meta", "MANIFEST.json")):  # 开发树
        if mp and os.path.isfile(mp):
            try:
                man = json.load(open(mp, encoding="utf-8"))
                print("  指纹来自: %s" % os.path.relpath(mp, ROOT))
                break
            except Exception as e:
                print("  (%s 读取失败: %s)" % (mp, e))
    ok_up = bool(ple_root) and os.path.isdir(ple_root)
    if ok_up:
        print("  目录存在: %s" % ple_root)
        verify_upstream(ple_root, man)
    else:
        print("  未配置（ARK_PLE_ROOT）。PLE 是运行必需的：引擎按 ple_index.json 里记录的")
        print("  字节偏移，直接到上游仓库的分片里 seek 读行。")
        if not UPSTREAM_REPO:
            print("  ⚠ 本包未内置上游仓库 id（发布者未填 ARKION_UPSTREAM_REPO）。请手动：")
            print("      1) 到魔搭搜索/打开 Qwen3.8-Flash-Next 的**官方仓库页**（就是你当初下载")
            print("         %s 的那个页面），复制它的 owner/name" % "D:\\qwen3.8-flash-next")
            print("      2) modelscope download <owner/name> --local-dir <目录>")
            print("      3) 重新运行本向导（或 set ARK_PLE_ROOT=<目录>）")
            print("    或者直接告诉我：set ARKION_UPSTREAM_REPO=<owner/name> 后重跑，本向导会自动下载。")
        else:
            dflt_ple = os.path.join(os.path.splitdrive(os.path.abspath(model_dir))[0] + os.sep,
                                    "qwen3.8-flash-next")
            if a.yes:
                ple_root = dflt_ple
            else:
                try:
                    t = input("  输入基座目录（回车用 %s）: " % dflt_ple).strip().strip('"')
                except EOFError:
                    t = ""
                ple_root = t or dflt_ple
            fg = free_gb(ple_root)
            print("  需要约 %.1f GB，该盘剩余 %.1f GB" % (UPSTREAM_GB, fg))
            if 0 <= fg < UPSTREAM_GB + 5:
                print("  ✗ 空间不足（这是最大的一块，335 GB）。")
                return 2
            if not a.check_only and have_cli("modelscope"):
                if a.yes or ask("  现在下载上游基座 %s（%.1f GB）？" % (UPSTREAM_REPO, UPSTREAM_GB)):
                    ms_download(UPSTREAM_REPO, ple_root, workers=4)
                    verify_upstream(ple_root, man)

    # ---- 5) 落配置 + 校验 + 启动 ----
    hr("[5/5] 写入配置并校验")
    write_local_cfg(model_dir, ple_root if (ple_root and os.path.isdir(ple_root)) else None)
    lm = os.path.join(HERE, "locate_model.py")
    if os.path.isfile(lm):
        print("  运行数据校验 ...")
        subprocess.call([sys.executable, lm, "--check", model_dir])
    print("""
  下一步：
      serve\\chat.bat                     交互对话
      serve\\chat.bat --no-think          不思考（首字快 20 倍）
      serve\\run_serve.bat                只起 HTTP 服务（OpenAI 兼容）
      run_gate_k3.bat                     自检门禁（期望 15/16 PASS）
  说明与排查见 docs\\OPERATIONS.md
""")
    if not a.check_only and (a.yes or ask("  现在直接开始对话？", default_no=False)):
        cb = os.path.join(HERE, "chat.bat")
        if os.path.isfile(cb):
            subprocess.call([cb, "--no-think"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
